FROM python:3.12.0
WORKDIR /app

COPY app.py /app
COPY requirements.txt /app

RUN pip install -r requirements.txt
EXPOSE 8080

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080", "--workers", "2"]