FROM python:3.8
WORKDIR /app

COPY app.py /app
COPY requirements.txt /app

RUN /opt/render/project/src/.venv/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt
EXPOSE 8000

CMD ["uvicorn", "app:app"]
